export const MULTIPLE_DEFAULT = 6
export const MULTIPLE_MIN = 4
export const MULTIPLE_MAX = 12
export const MULTIPLE_STEP = 0.1

export const EXIT_MULTIPLE_DEFAULT = 6
export const EXIT_DEFAULT_YEAR = 2006

export const SENIOR_DEBT_DEFAULT = 10000
export const SUBORDINATED_DEBT_DEFAULT = 4000
export const SENIOR_DEBT_INTEREST_RATE_DEFAULT = 7.5
export const SUBORDINATED_DEBT_INTEREST_RATE_DEFAULT = 9.0
export const FINANCING_FEES_RATE_DEFAULT = 2.0
export const ADVISORY_FEE_RATE_DEFAULT = 3.0
export const TAX_RATE_DEFAULT = 25

export const MANAGEMENT_ROLLOVER_RATE_DEFAULT = 50
export const MANAGEMENT_ROLLOVER_MIN = 20
export const MANAGEMENT_ROLLOVER_MAX = 80
export const MANAGEMENT_ROLLOVER_STEP = 1


